const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname,'..');
const assets = [
  { id:'finial.acorn', kind:'finial', file:'artwork/finial/acorn.svg', frame:{viewBox:'-48 -124 96 124',mateWidth:48,embedDepth:21}, confidence:'reference-derived' },
  { id:'finial.ball', kind:'finial', file:'artwork/finial/ball.svg', frame:{viewBox:'-50 -114 100 114',mateWidth:48,embedDepth:18}, confidence:'reference-derived' },
  { id:'finial.deco-ball', kind:'finial', file:'artwork/finial/deco-ball.svg', frame:{viewBox:'-52 -118 104 118',mateWidth:50,embedDepth:17}, confidence:'reference-derived' },
  { id:'finial.dome-cap', kind:'finial', file:'artwork/finial/dome-cap.svg', frame:{viewBox:'-50 -58 100 58',mateWidth:76,embedDepth:15}, confidence:'representative-approved' },
  { id:'finial.pineapple', kind:'finial', file:'artwork/finial/pineapple.svg', frame:{viewBox:'-50 -200 100 200',mateWidth:81,embedDepth:32.5}, confidence:'proportion-verified' },
  { id:'post.fluted-round', kind:'post', file:'artwork/post/fluted-round.svg', frame:{viewBox:'0 0 100 1000',safeBand:{y0:50,y1:950}}, confidence:'reference-derived' },
  { id:'post.smooth-round', kind:'post', file:'artwork/post/smooth-round.svg', frame:{viewBox:'0 0 100 1000',safeBand:{y0:50,y1:950}}, confidence:'representative-approved' },
  { id:'post.square', kind:'post', file:'artwork/post/square.svg', frame:{viewBox:'0 0 100 1000',safeBand:{y0:0,y1:1000}}, confidence:'reference-derived' }
].sort((a,b)=>a.id.localeCompare(b.id));

function sanitize(source,prefix) {
  const rootMatch=source.match(/<svg\b([^>]*)>([\s\S]*?)<\/svg>\s*$/i);
  if(!rootMatch) throw new Error('Invalid SVG root');
  let markup=rootMatch[2]
    .replace(/<!--[\s\S]*?-->/g,'')
    .replace(/<(title|desc|metadata|script|foreignObject)\b[^>]*>[\s\S]*?<\/\1>/gi,'')
    .replace(/<image\b[^>]*(?:\/>|>[\s\S]*?<\/image>)/gi,'')
    .replace(/\sdata-[\w:-]+\s*=\s*("[^"]*"|'[^']*')/gi,'')
    .replace(/\saria-label\s*=\s*("[^"]*"|'[^']*')/gi,'')
    .replace(/\son[\w:-]+\s*=\s*("[^"]*"|'[^']*')/gi,'');
  const ids=[];
  markup=markup.replace(/\bid\s*=\s*(["'])([^"']+)\1/g,(_,quote,id)=>{
    const replacement=`${prefix}-i${ids.length+1}`;
    ids.push([id,replacement]);
    return `id=${quote}${replacement}${quote}`;
  });
  for(const [oldId,newId] of ids) {
    const escaped=oldId.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
    markup=markup
      .replace(new RegExp(`url\\(\\s*#${escaped}\\s*\\)`,'g'),`url(#${newId})`)
      .replace(new RegExp(`((?:xlink:)?href\\s*=\\s*["'])#${escaped}(["'])`,'g'),`$1#${newId}$2`);
  }
  return markup.trim().replace(/\r\n/g,'\n');
}

function buildArtwork() {
  const registry={};
  assets.forEach((asset,index)=>{
    const source=fs.readFileSync(path.join(root,asset.file),'utf8');
    const viewBox=source.match(/\bviewBox\s*=\s*["']([^"']+)["']/i)?.[1];
    if(viewBox!==asset.frame.viewBox) throw new Error(`${asset.file}: expected viewBox ${asset.frame.viewBox}, found ${viewBox}`);
    const markup=sanitize(source,`aa-a${String(index+1).padStart(2,'0')}`);
    if(/data-|<title|<desc|<metadata|<image|<script|foreignObject|\bOPP\b|\bTCP\b|\bSKU\b/i.test(markup)) {
      throw new Error(`${asset.file}: unsafe content survived sanitization`);
    }
    registry[asset.id]={id:asset.id,kind:asset.kind,markup,frame:asset.frame,confidence:asset.confidence,
      provenance:{assetId:path.basename(asset.file,'.svg'),assetFile:asset.file,notes:'Approved Phase 2 vector library; sanitized at build time.'}};
  });
  return `// Generated by tools/build-artwork.cjs. Do not edit.\nwindow.AA_ART = Object.freeze(${JSON.stringify(registry,null,2)});\n`;
}

if(require.main===module) fs.writeFileSync(path.join(root,'artwork.js'),buildArtwork());
module.exports={buildArtwork,sanitize,assets};
